### PR TITLE
Adjusted envorinment variable names

### LINKED ISSUE #218: Setup-environment variable names
**Describe the bug**
Environment variable names are not in alignment with the names given in the env file [example](https://github.com/os-climate/os_c_data_commons/blob/main/docs/credentials.env) :
 
**To Reproduce**
Run these notebook:
- [setup-expt](https://github.com/os-climate/aicoe-osc-demo/blob/master/notebooks/demo2/setup_experiments_default_pdfs.ipynb)
- [pdf_txt_ext](https://github.com/os-climate/aicoe-osc-demo/blob/master/notebooks/demo2/pdf_text_extraction.ipynb)
- [infer relevance](https://github.com/os-climate/aicoe-osc-demo/blob/master/notebooks/demo2/infer_relevance.ipynb)
- [infer kpi](https://github.com/os-climate/aicoe-osc-demo/blob/master/notebooks/demo2/infer_kpi.ipynb)
- [create result table](https://github.com/os-climate/aicoe-osc-demo/blob/master/notebooks/demo2/create_results_table.ipynb)

### PR DESCRIPTION
**Pull request by suppathak**
Closes #218

### CODE REVIEW

**Review by Shreyanand — COMMENTED** [review]
These changes look good, thanks :) Will all the notebooks follow the same env variable names after this PR? let's make sure the standard is followed across!

Make sure the DCO check is satisfied, you'll have to add signature in the commit message like [here](https://github.com/os-climate/aicoe-osc-demo/pull/216/commits/29077cb9934f76a1ec489999bbd9699bc3acbb74)

**Comment by erikerlandson** [comment]
looks like the commits need to be signed, like `commit -asm ....`

**Pull request merged**
