### PR TITLE
Downgrade markupsafe to fix soft_unicode deprecation error.

### PR DESCRIPTION
**Pull request by chauhankaranraj**
Fixes os-climate/os_c_data_commons#162

### CODE REVIEW

**Review by Shreyanand — COMMENTED** [review]
/approve /hold

**Comment by chauhankaranraj** [comment]
image builds and runs fine. can be tested by running
```
docker build . -f Dockerfile -t quay.io/kachau/aicoe-osc-demo:your-tag
```

**Review by harshad16 — COMMENTED** [review]
lgtm :+1:

**Pull request merged**
