### PR TITLE
Add manifests for GPU image build

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

Fixes: https://github.com/os-climate/aicoe-osc-demo/issues/128

Depends-On: https://github.com/os-climate/neural-magic-notebook/pull/1

### CODE REVIEW

**Review by erikerlandson — APPROVED** [review]

**Comment by pacospace** [comment]
> /hold need to reference all ODH repos. cc @harshad16

updated @harshad16, PTAL

**Review by harshad16 — APPROVED** [review]
looks neat
lgtm :+1:

**Comment by MichaelTiemannOSC** [comment]
Given that this is all merged, why is it not listed as closed, so that automation can mark the dependent issue https://github.com/os-climate/aicoe-osc-demo/issues/128 as Done (instead of leaving it hanging as an apparently unfinished sprint 2022-02-17 work item)?

**Pull request merged**
