### PR TITLE
Update demo2 inference pipeline and README

### PR DESCRIPTION
**Pull request by chauhankaranraj**
This PR
* Moves the create-tables notebook to demo2
* Updates create-tables notebook to use file paths from config.py, now that they're in the same dir
* Adds the create-tables step to the inference pipeline for demo2
* Updates README to reflect changes in demo2

### CODE REVIEW

**Review by oindrillac — APPROVED** [review]
/lgtm 👍 Thanks!

do we have a KFP link which tests out this pipeline?

**Review by aakankshaduggal — COMMENTED** [review]
/lgtm

**Comment by chauhankaranraj** [comment]
> do we have a KFP link which tests out this pipeline?

Ah yes ofc, I should have included that in the PR, here's the [kfp run](http://ml-pipeline-ui-kubeflow.apps.odh-cl1.apps.os-climate.org/pipeline/#/runs/details/f5556e22-bae1-4c4f-a231-b23f9add5351).

Interestingly, it seems to work well for the pdfs in `samples_4` key on s3, but when run for pdfs in `samples_10`, we get a pandas error in the final step. We can debug this and send a separate PR?

**Comment by oindrillac** [comment]
> Ah yes ofc, I should have included that in the PR, here's the [kfp run](http://ml-pipeline-ui-kubeflow.apps.odh-cl1.apps.os-climate.org/pipeline/#/runs/details/f5556e22-bae1-4c4f-a231-b23f9add5351).

Thank you! 👍 

> Interestingly, it seems to work well for the pdfs in `samples_4` key on s3, but when [run](http://ml-pipeline-ui-kubeflow.apps.odh-cl1.apps.os-climate.org/pipeline/#/runs/details/c32c632f-0f77-4548-a6b8-1cfaf57c5124) for pdfs in `samples_10`, we get a pandas error in the final step. We can debug this and send a separate PR?

Sure, that sounds good. Maybe related to this? https://github.com/os-climate/aicoe-osc-demo/issues/97

Can we also please squash commits on this?

**Comment by chauhankaranraj** [comment]
> Sure, that sounds good. Maybe related to this? #97

Yeah, maybe :thinking:

> Can we also please squash commits on this?

Of course, done!

**Pull request merged**
