### PR TITLE
Add demo2 superset dashboard

### PR DESCRIPTION
**Pull request by Shreyanand**
Relevant issues #105 

In this PR, I add a WIP [dashboard](https://superset-secure-odh-superset.apps.odh-cl1.apps.os-climate.org/superset/dashboard/15/) for visualizing results from the output of demo 2.

Let me know if you have more ideas on how to make the dashboard look better.

### CODE REVIEW

**Comment by aakankshaduggal** [comment]
I think the dashboard is a good start, we can visualize the answers in a prettier way using a word cloud visualization. Please find the chart for the same, [here](https://superset-secure-odh-superset.apps.odh-cl1.apps.os-climate.org/superset/explore/?form_data=%7B%22slice_id%22%3A%2073%7D). 

image

**Comment by aakankshaduggal** [comment]
Another correlation diagram could map source (KPI) to target (Answer). We can also find what all kpis map to the same answers as shown in the diagram here -
image
Please find the chart for the same, [here](https://superset-secure-odh-superset.apps.odh-cl1.apps.os-climate.org/superset/explore/?form_data=%7B%22slice_id%22%3A%2074%7D). Looks cluttered when we display for all but can be super useful if we filter.

**Comment by Shreyanand** [comment]
@aakankshaduggal We can try adding your suggestions in the dashboard but my hunch is that they wouldn't convey a lot of information since there is a lot of noise in the output predictions. For example, each question has several answers based on probability scores. We need some kind of post processing of this output and model performance improvements as well.

For the first version that shows a way to query table Trino tables with pdf names and kpi questions, I have added the latest dashboard that can be reviewed.

**Pull request merged**
