### PR TITLE
Add new diagram

### PR DESCRIPTION
**Pull request by Shreyanand**
Updates the architecture diagram with the training pipeline sequence and notebooks.

Related #180

### CODE REVIEW

**Comment by oindrillac** [comment]
Updates look good! Was easy to comprehend the logical data flow

Minor visual nits:

The arrows pointing to the infer relevance notebook are a little off, can we please align and fix those?

Second point is optional : I see there are 2 arraows pointing to ceph from each side, I understand why its 2 instead of 1, but it might be cleaner to make it 1 just coz they're merging in the upper section anyway.

demo2-viz

**Review by oindrillac — COMMENTED** [review]
Looks good! Please see comment for minor suggestions

**Comment by Shreyanand** [comment]
> Looks good! Please see comment for minor suggestions

Thanks for the review! Added the changes. For point 2, I separated the merge from two arrows as that is more consistent with the actual flow.

**Review by oindrillac — APPROVED** [review]
/lgtm
/approve

**Comment by Shreyanand** [comment]
@harshad16 why wouldn't this auto-merge, it seems to have everything required...

**Comment by harshad16** [comment]
>  why wouldn't this auto-merge, it seems to have everything required...

seems like the CI user [sesheta](https://github.com/orgs/os-climate/people?query=sesh) doesn't have the privilege to merge the PR in this org.
one would have to allow the user.

**Comment by Shreyanand** [comment]
@harshad16 if you look at a previous [PR](https://github.com/os-climate/aicoe-osc-demo/pull/177), it was merged by sesheta. Did something change here? How can we allow it to merge PRs?

**Comment by harshad16** [comment]
>  Did something change here? How can we allow it to merge PRs?

ack, it hard to deduced with my current privileges 
i will take a much closer look.
it just seems like branch protection was added to the repo, which seemed to me as the reason.
however i will double check on this scenario.

**Comment by harshad16** [comment]
seems like there is an issue on deployment side of the CI
hopefuly resolution of that , would fix the non-merge action of the CI.
will keep you posted,
howver if PR is critical and in hurry, please merge it manually.

**Pull request merged**
