### PR TITLE
[WIP] add inference to elyra pipeline

### LINKED ISSUE #79: Run data processing elyra pipeline on 100 pdfs
To determine the scalability of the `demo2` data processing elyra pipeline, we want to run the on a small sample (about 100 pdfs) present in the`redhat-osc-physical-landing-647521352890` bucket which currently has 8651 pdfs at the key `redhat-osc-physicalrisk-upload/S&PGlobal_ESG/`

Acceptance Criteria:
- [ ] Modify demo2 notebooks to process multiple pdfs and store the results on S3.

### LINKED ISSUE #84: Demo2: Add relevance infer notebook to the pipeline
Once #83 is merged, we should add the relevance inference to the Elyra pipeline. This would include the following changes:

1. Create a new image release to reflect changes in the src folder
2. Automation flow: Update paths in the notebook to work in both pipeline and dev env.

### PR DESCRIPTION
**Pull request by oindrillac**
In this PR, we extend the demo 2 to also include the inference notebook and also run the demo 2 on a larger sample of pdfs.

We have tested it out by running them using Elyra & KFP:
- Run comprising of 3 pdfs -
- Run comprising of 10 pdfs -

resolves #84 
resolves #79

### CODE REVIEW

**Comment by MichaelClifford** [comment]
@oindrillac is this still WIP? or ok to merge?

**Comment by oindrillac** [comment]
> @oindrillac is this still WIP? or ok to merge?

@MichaelClifford still WIP, we're waiting for some tests (runs) to succesfully complete

**Comment by oindrillac** [comment]
- We noticed that the pipeline fails on certain pdfs with EOF errors, so we would need more pdf error handling in the download functions before moving ahead with this PR. 

- Moreover, the curation notebooks only rely on certain annotated pdfs, and currently do not run at scale on multiple reports, so it probably makes more sense to add the text extraction and inference notebook as a separate pipeline to this repo which can scale on a larger number of reports.

**Comment by MichaelClifford** [comment]
@oindrillac is there a separate issue to track item 1? 
>pipeline fails on certain pdfs with EOF errors, so we would need more pdf error handling in the download functions

**Comment by MichaelClifford** [comment]
> the curation notebooks only rely on certain annotated pdfs

Is this because its part of the training pipeline, where we have some existing annotated labels we are adding to the data? 

I think it makes sense to have 2 pipelines: one for curation and training and one for extraction and inference. WDYT?

**Comment by oindrillac** [comment]
> @oindrillac is there a separate issue to track item 1?
> 
> > pipeline fails on certain pdfs with EOF errors, so we would need more pdf error handling in the download functions

opened one 👍

**Comment by oindrillac** [comment]
> Is this because its part of the training pipeline, where we have some existing annotated labels we are adding to the data?

> I think it makes sense to have 2 pipelines: one for curation and training and one for extraction and inference. WDYT?

Yes, the curation notebooks work only with a certain report currently for which annotated labels exist, hence, it fails when made to run on multiple reports. Yeah, it makes sense to split it that way.

**Comment by oindrillac** [comment]
closing this PR in favor of #104 and to avoid merge conflicts

**Pull request closed without merging**
