### PR TITLE
Update negative sampling class to prevent KeyErrors

### PR DESCRIPTION
**Pull request by chauhankaranraj**
Curation notebook sometimes errored out because the negative samples creation function selected invalid PDF page numbers. This PR fixes that error by making sure only valid page numbers are sampled.
This PR also rerun curation nb for 145 samples.

Co-authored-by: Shrey Anand <shanand@redhat.com>
Signed-off-by: Karanraj Chauhan <kachau@redhat.com>

### CODE REVIEW

**Review by erikerlandson — APPROVED** [review]

**Comment by chauhankaranraj** [comment]
Rebased on master and resolved conflicts. Not sure why the precommit check is timing out - seems to pass when manually run on JH instance.

/retest

**Comment by chauhankaranraj** [comment]
> the cluster where prow runs (pre-commit checks) is having some issues ([operate-first/operations#479](https://github.com/operate-first/operations/issues/479)).

Hey @codificat, so now precommit check runs correctly but I see PipelineRunTimeout on the build check. Would you happen to have any estimate on when we can expect the cluster issues to be resolved?

**Comment by chauhankaranraj** [comment]
Manually merging since the PR has been approved and tests are passing on JH, just the CI seems to be blocked

**Pull request merged**
